-- PostgreSQL / Supabase schema for quanlylophoc
-- Paste this file into the Supabase SQL Editor and run it once.

BEGIN;

DROP TABLE IF EXISTS public.ai_feedback CASCADE;
DROP TABLE IF EXISTS public.submissions CASCADE;
DROP TABLE IF EXISTS public.assignments CASCADE;
DROP TABLE IF EXISTS public.attendance CASCADE;
DROP TABLE IF EXISTS public.sessions CASCADE;
DROP TABLE IF EXISTS public.class_students CASCADE;
DROP TABLE IF EXISTS public.classes CASCADE;
DROP TABLE IF EXISTS public.students CASCADE;
DROP TABLE IF EXISTS public.teachers CASCADE;


CREATE TABLE public.teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    department VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE public.students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_code VARCHAR(20) NOT NULL UNIQUE,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    class_name VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE public.classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_code VARCHAR(20) NOT NULL UNIQUE,
    class_name VARCHAR(100) NOT NULL,
    subject_name VARCHAR(100) NOT NULL,
    teacher_id BIGINT NOT NULL,
    semester VARCHAR(20),
    school_year VARCHAR(20),
    room VARCHAR(50),
    schedule_info VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_classes_teacher
        FOREIGN KEY (teacher_id) REFERENCES public.teachers(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


CREATE TABLE public.class_students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_class_students_class
        FOREIGN KEY (class_id) REFERENCES public.classes(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_class_students_student
        FOREIGN KEY (student_id) REFERENCES public.students(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT uq_class_student UNIQUE (class_id, student_id)
);


CREATE TABLE public.sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT NOT NULL,
    session_title VARCHAR(100),
    session_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    qr_token VARCHAR(255) NOT NULL UNIQUE,
    qr_expired_at TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_sessions_class
        FOREIGN KEY (class_id) REFERENCES public.classes(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


CREATE TABLE public.attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    checkin_time TIMESTAMPTZ,
    attendance_status TEXT NOT NULL DEFAULT 'absent' CHECK (attendance_status IN ('present', 'late', 'absent')),
    note VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_attendance_session
        FOREIGN KEY (session_id) REFERENCES public.sessions(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_attendance_student
        FOREIGN KEY (student_id) REFERENCES public.students(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT uq_attendance_session_student UNIQUE (session_id, student_id)
);


CREATE TABLE public.assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    due_date TIMESTAMPTZ NOT NULL,
    attachment_path VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_assignments_class
        FOREIGN KEY (class_id) REFERENCES public.classes(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


CREATE TABLE public.submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    file_path VARCHAR(255),
    submission_text TEXT,
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status TEXT NOT NULL DEFAULT 'submitted' CHECK (status IN ('submitted', 'late', 'missing')),
    teacher_score NUMERIC(5, 2),
    teacher_comment TEXT,
    CONSTRAINT fk_submissions_assignment
        FOREIGN KEY (assignment_id) REFERENCES public.assignments(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_submissions_student
        FOREIGN KEY (student_id) REFERENCES public.students(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT uq_submission_assignment_student UNIQUE (assignment_id, student_id)
);


CREATE TABLE public.ai_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL UNIQUE,
    completion_level INT,
    suggested_comment TEXT,
    missing_content TEXT,
    similarity_warning TEXT,
    ai_score NUMERIC(5, 2),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ai_feedback_submission
        FOREIGN KEY (submission_id) REFERENCES public.submissions(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


CREATE INDEX idx_classes_teacher_id ON public.classes (teacher_id);
CREATE INDEX idx_class_students_class_id ON public.class_students (class_id);
CREATE INDEX idx_class_students_student_id ON public.class_students (student_id);
CREATE INDEX idx_sessions_class_id_date ON public.sessions (class_id, session_date);
CREATE INDEX idx_attendance_session_id ON public.attendance (session_id);
CREATE INDEX idx_attendance_student_id ON public.attendance (student_id);
CREATE INDEX idx_assignments_class_id_due_date ON public.assignments (class_id, due_date);
CREATE INDEX idx_submissions_assignment_id ON public.submissions (assignment_id);
CREATE INDEX idx_submissions_student_id_status ON public.submissions (student_id, status);
CREATE INDEX idx_ai_feedback_submission_id ON public.ai_feedback (submission_id);


INSERT INTO public.teachers (id, full_name, email, password, phone, department)
VALUES
    (1, 'Nguyễn Việt Tùng', 'tungnv@hust.edu.vn', 'scrypt:32768:8:1$4wWuQIYn7x6stGZc$1134accca30de451e7b580a24470266becdd1ac8995c195007176a5352d314806d8789f12f059de32060f846a2a45db6f1226f69603a51adfa9593d2e0fb4fa4', '0123456789', 'MICA');


INSERT INTO public.students (id, student_code, full_name, email, password, phone, class_name)
VALUES
    (1, '20231556', 'Nguyễn Tuấn Anh', 'anh.nt231556@sis.hust.edu.vn', 'scrypt:32768:8:1$6VVdYKAFOBh8x80M$3b379ab7c6250a23d568670a83158fc9080940b82f686cdd7a795ba39ff6b05c595820356ce233a544a23fa3357d6d79fe0d3e0a2f5057436b35ab02ec13316a', '0911111111', 'K68-ED2'),
    (2, '20235555', 'Nguyễn Thành Luân', 'luannt@sis.hust.edu.vn', 'scrypt:32768:8:1$6VVdYKAFOBh8x80M$3b379ab7c6250a23d568670a83158fc9080940b82f686cdd7a795ba39ff6b05c595820356ce233a544a23fa3357d6d79fe0d3e0a2f5057436b35ab02ec13316a', '0922222222', 'K68-ED2'),
    (3, '20237777', 'Lê Anh Đức', 'ducla@sis.hust.edu.vn', 'scrypt:32768:8:1$6VVdYKAFOBh8x80M$3b379ab7c6250a23d568670a83158fc9080940b82f686cdd7a795ba39ff6b05c595820356ce233a544a23fa3357d6d79fe0d3e0a2f5057436b35ab02ec13316a', '0944444444', 'K68-ED2');


INSERT INTO public.classes (id, class_code, class_name, subject_name, teacher_id, semester, school_year, room, schedule_info)
VALUES
    (1, 'ED-K68', 'ED2-K68', 'Thiết kế và lập trình web', 1, 'Kỳ 20252', '2025-2026', 'D9-303', 'Thứ 3 - Tiết 1-3');


INSERT INTO public.class_students (class_id, student_id)
VALUES
    (1, 1),
    (1, 2),
    (1, 3);


INSERT INTO public.sessions (id, class_id, session_title, session_date, start_time, end_time, qr_token, qr_expired_at, status)
VALUES
    (1, 1, 'Buổi học 1', CURRENT_DATE, '06:45:00', '09:10:00', 'QR_TOKEN_SAMPLE_001', NOW() + INTERVAL '15 minutes', 'open');


INSERT INTO public.attendance (session_id, student_id, checkin_time, attendance_status, note)
VALUES
    (1, 1, NOW(), 'present', 'Đúng giờ'),
    (1, 2, NOW(), 'late', 'Trễ 10 phút'),
    (1, 3, NULL, 'absent', 'Vắng');


INSERT INTO public.assignments (id, class_id, title, description, due_date, attachment_path)
VALUES
    (1, 1, 'Bài tập 1', 'Thiết kế giao diện đăng nhập bằng HTML/CSS', NOW() + INTERVAL '7 days', NULL);


INSERT INTO public.submissions (assignment_id, student_id, file_path, submission_text, submitted_at, status, teacher_score, teacher_comment)
VALUES
    (1, 1, 'static/uploads/baitap1_tuananh.pdf', 'Bài làm của Nguyễn Tuấn Anh', NOW(), 'submitted', 9.50, 'Đạt yêu cầu'),
    (1, 2, 'static/uploads/baitap1_duc.pdf', 'Bài làm của Lê Anh Đức', NOW(), 'submitted', NULL, NULL),
    (1, 3, NULL, NULL, NOW(), 'missing', NULL, NULL);


INSERT INTO public.ai_feedback (submission_id, completion_level, suggested_comment, missing_content, similarity_warning, ai_score)
VALUES
    (1, 85, 'Bài làm ổn, giao diện rõ ràng.', 'Cần bổ sung validation form.', 'Không phát hiện trùng lặp cao.', 8.00);


SELECT setval(pg_get_serial_sequence('public.teachers', 'id'), COALESCE(MAX(id), 1), true) FROM public.teachers;
SELECT setval(pg_get_serial_sequence('public.students', 'id'), COALESCE(MAX(id), 1), true) FROM public.students;
SELECT setval(pg_get_serial_sequence('public.classes', 'id'), COALESCE(MAX(id), 1), true) FROM public.classes;
SELECT setval(pg_get_serial_sequence('public.class_students', 'id'), COALESCE(MAX(id), 1), true) FROM public.class_students;
SELECT setval(pg_get_serial_sequence('public.sessions', 'id'), COALESCE(MAX(id), 1), true) FROM public.sessions;
SELECT setval(pg_get_serial_sequence('public.attendance', 'id'), COALESCE(MAX(id), 1), true) FROM public.attendance;
SELECT setval(pg_get_serial_sequence('public.assignments', 'id'), COALESCE(MAX(id), 1), true) FROM public.assignments;
SELECT setval(pg_get_serial_sequence('public.submissions', 'id'), COALESCE(MAX(id), 1), true) FROM public.submissions;
SELECT setval(pg_get_serial_sequence('public.ai_feedback', 'id'), COALESCE(MAX(id), 1), true) FROM public.ai_feedback;

COMMIT;
